package io.kination.vine;

import org.junit.jupiter.api.Test;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

class VineJniIntegrationTest {

    @Test
    void testReadDataArrow() {
        try {
            // Path to the test table generated by generate-test-data
            String tablePath = Paths.get("src/test/resources/test_table").toAbsolutePath().toString();
            
            // 1. Read Arrow IPC bytes via JNI (Using Compatibility Mode for Java 14)
            byte[] arrowData = VineModule.readDataArrow(tablePath, VineModule.COMPAT_MODE_JAVA14);
            
            assertNotNull(arrowData, "JNI readDataArrow returned null");
            assertTrue(arrowData.length > 0, "JNI readDataArrow returned empty array");
            
            // 2. Define columns to extract (matching generate-test-data)
            List<VineColumnHandle> columns = List.of(
                new VineColumnHandle("id", io.trino.spi.type.IntegerType.INTEGER, 0),
                new VineColumnHandle("name", io.trino.spi.type.VarcharType.VARCHAR, 1),
                new VineColumnHandle("score", io.trino.spi.type.DoubleType.DOUBLE, 2),
                new VineColumnHandle("active", io.trino.spi.type.BooleanType.BOOLEAN, 3)
            );
            
            // 3. Convert Arrow to Rows
            Object[][] rows = VineArrowConverter.arrowToRows(arrowData, columns);
            
            assertEquals(3, rows.length, "Expected 3 rows from test data");
            
            // Row 1: 1, "Alice", 95.5, true
            assertEquals(1L, rows[0][0]);
            assertEquals("Alice", rows[0][1]);
            assertEquals(95.5, rows[0][2]);
            assertEquals(true, rows[0][3]);
            
            System.out.println("Integration test passed: successfully read 3 rows via JNI");
        } catch (Exception e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }
}
